### ISSUE TITLE
When trying to access webapp from browser got an issue

### ISSUE THREAD

**Issue by vuongc** [EIP-SAM/SAM-Solution-Node-js#167]
The error I when trying to access the webapp from browser are this one:

```
Error: no such file or directory
   at MemoryFileSystem.readFileSync (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
   at app.get (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/server/middlewares/frontendMiddleware.js:25:21)
   at Layer.handle [as handle_request] (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/layer.js:95:5)
   at /Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/index.js:277:22
   at param (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/index.js:349:14)
   at param (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/index.js:410:3)
   at next (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/index.js:271:10)
   at middleware (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/webpack-hot-middleware/middleware.js:39:48)
   at Layer.handle [as handle_request] (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/index.js:312:13)
   at /Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/express/lib/router/index.js:330:12)
```

**Comment by vuongc** [comment]
This error was linked to issue [#166](https://github.com/EIP-SAM/SAM-Solution-Server/issues/166), so when fixing this issue it also solve issue #167
