### ISSUE TITLE
Webpack Invalid configuration object

### ISSUE THREAD

**Issue by vuongc** [EIP-SAM/SAM-Solution-Node-js#241]
## Issue

When launching webapp an error appear and then the webapp crashed.
## Error

``` shell```
/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/webpack/lib/webpack.js:16
        throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
        ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'progress'. These properties are valid:
   object { amd?, bail?, cache?, context?, devServer?, devtool?, entry, externals?, loader?, module?, name?, dependencies?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
 - configuration.resolve has an unknown property 'packageMains'. These properties are valid:
   object { modules?, descriptionFiles?, plugins?, mainFields?, aliasFields?, mainFiles?, extensions?, enforceExtension?, moduleExtensions?, enforceModuleExtension?, alias?, symlinks?, unsafeCache?, cachePredicate?, fileSystem?, resolver? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/node_modules/webpack/lib/webpack.js:16:9)
    at addDevMiddlewares (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/server/middlewares/frontendMiddleware.js:10:20)
    at module.exports (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/server/middlewares/frontendMiddleware.js:52:5)
    at Object.<anonymous> (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/webapp/server/index.js:20:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```
## Fix

In file `webapp/internals/webpack.base.babel.js` removing the line:
- `postcss: () => options.postcssPlugins,` => l.73
- `'',` => l.77
- `packageMains: ['jsnext:main','main',],` => l.82-85
- `progress: true,` => l90

The webapp work after, it must be because the configuration has been updated in the new version of `webpack2-beta`

**Comment by vuongc** [comment]
No pull request will be submitted until further test, because it seems like this issue shows up only on MacOSX.

**Comment by BernardJeremy** [comment]
I postpone this issue to the next milestone since its scope seems to be very limited.

**Comment by vuongc** [comment]
Issue is not only happening on `MacOSX`
