### ISSUE TITLE
Unable to reach webapp when using main server

### ISSUE THREAD

**Issue by BernardJeremy** [EIP-SAM/SAM-Solution-Node-js#54]
API server should serve the webapp through its static route.

**Comment by Grenadingue** [comment]
After executing this instructions I'm able to reach, at least, the login page from the main server (`localhost:8080`)

```
$ cd webapp
$ npm run build
$ cd ..
$ npm start
```

**Comment by Grenadingue** [comment]
If I try to login via this way, I cannot login and I get multiple times this error on server side

```
[2016-07-18T15:45:43.645Z]  INFO: sam-logger/7241 on Nico-PC: Listening on port 8080
Error: "value" required in setHeader("Access-Control-Allow-Origin", value)
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at /run/media/nicolas/TAF/eip/SAM-Solution-Server/libs/express.js:18:9
    at Layer.handle [as handle_request] (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:312:13)
    at /run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:330:12)
    at next (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:271:10)
    at cors (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/cors/lib/index.js:178:7)
    at /run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/cors/lib/index.js:228:17
    at originCallback (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/cors/lib/index.js:217:15)
    at /run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/cors/lib/index.js:222:13
    at optionsCallback (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/cors/lib/index.js:203:9)
    at /run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/cors/lib/index.js:208:7
    at Layer.handle [as handle_request] (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:312:13)
    at /run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:330:12)
    at next (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:271:10)
    at /run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/connect-flash/lib/flash.js:21:5
    at Layer.handle [as handle_request] (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:312:13)
    at /run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:330:12)
    at next (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/body-parser/lib/types/urlencoded.js:88:40)
    at Layer.handle [as handle_request] (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:312:13)
    at /run/media/nicolas/TAF/eip/SAM-Solution-Server/node_modules/express/lib/router/index.js:280:7
```

You can even note that there is no login attempt on server side

**Comment by BernardJeremy** [comment]
I still think it's better to use two different process (and port).
It will be easier for us to develop and fully transparent for the user if commands like `npm install` and `npm start` install and run everything.

**Comment by Grenadingue** [comment]
Okay, we need to find the "production" way of starting the webapp, actually the webapp server is natively running in "development" mode

**Comment by BernardJeremy** [comment]
Will be fixed by #511
