### ISSUE TITLE
Server does not launch with npm start

### ISSUE THREAD

**Issue by vuongc** [EIP-SAM/SAM-Solution-Node-js#82]
## Issue:

When trying to launch server, do not receive any feedback and cannot access to the server from the webapp. The server is not listening.
## Output from logs put at each step on the server initialization:

<img width="1235" alt="screen shot 2016-07-18 at 4 23 39 pm" src="https://cloud.githubusercontent.com/assets/6729188/16917967/0d697ada-4d04-11e6-9de4-43b82834ad09.png">
## Entry point:

``` javascript
// retrieve configuration from main config file
const config = require('./config/base.config.json');
config.rootFolder = __dirname;

var app = require('./libs/express')(config);
var logger = require('./managers/log');

console.log('Before listening');

require('./models/init')().then(function () {
  console.log('model init then');
  require('./routes')(app, config);
  var server = app.listen(config.port, function () {
    var log = logger.launchLog();

    log.info('Listening on port ' + config.port);
  });

  var socket = require('./daemon/').init(server);
});

console.log('After listening');
```
## Initialization of models:

``` javascript
module.exports = function init() {
  return new Promise(function (fulfill, reject) {

    require('./users').sync().then(function () {
      console.log('users sync');
      require('./saveScheduled').sync().then(function () {
        console.log('saveScheduled sync');
        require('./save').sync().then(function () {
          console.log('save sync');
          require('./restore').sync().then(function () {
            console.log('restore sync');
            require('./groups').sync().then(function () {
              console.log('groups sync');
              require('./usersGroupsRelations').sync().then(function () {
                console.log('usersGroupsRelations sync');
                fulfill();
              });
            });
          });
        });
      });
    });

  });
};
```
## Initialization of routes:

``` javascript
module.exports = function initRoutes(app, conf) {
  console.log('before passport libs');
  const passport = require('../libs/passport')(app);

  console.log('route init');

  require('./routes')(app, conf, passport);
  require('./users')(app, conf, passport);
  require('./statistic')(app, conf);
  require('./restore')(app);
  require('./save')(app);
  require('./log')(app);

  console.log('Route end');
};
```
## Users managers:

``` javascript
console.log('Start users');

//
// Load librarie(s) used in this manager
//
const crypto = require('../libs/crypto');
console.load('After Load library crypto');
const passwordGenerator = require('password-generator');
console.load('After Load library password-generator');
const emailValidator = require('email-validator');
console.load('After Load library email-validator');

console.load('After Load librarie(s) used in this manager');

//
// Load config variable(s) from config file
//
const salt = require('../config/base.config.json').salt;
```
## Crypto file:

``` javascript
try {
  console.log('crypto ok');
  module.exports = require('crypto');
} catch (err) {
  console.log('Fatal error: Cryptographic support is disabled, aborting');
  console.log(err.message);
  process.exit(1);
}
```

**Comment by Grenadingue** [comment]
Can you try with this entry point and then give me the output log ? @vuongc 

``` javascript
// retrieve configuration from main config file
const config = require('./config/base.config.json');
config.rootFolder = __dirname;

var app = require('./libs/express')(config);
var logger = require('./managers/log');

console.log('Before listening');

require('./routes')(app, config);
var server = app.listen(config.port, function () {
  var log = logger.launchLog();

  log.info('Listening on port ' + config.port);
});

var socket = require('./daemon/').init(server);

console.log('After listening');
```

The errors were certainly hidden by the `require('./models/init')()` promise

**Comment by vuongc** [comment]
This is what I get

``` javascript
Before listening
before passport libs
Start users
crypto ok
After Load library crypto
After Load library password-generator
After Load library email-validator
After Load librarie(s) used in this manager
passport before init
passport start
route init
/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/managers/save.js:45
  let usersId = req.body.usersId;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/controllers/save.js:4:19)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/routes/save.js:5:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at initRoutes (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/routes/index.js:11:3)
    at Object.<anonymous> (/Users/christophervuong/workspace/epitech/eip/SAM-Solution-Server/server.js:33:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by Grenadingue** [comment]
```
$ node --version
```

please

**Comment by vuongc** [comment]
v5.1.0

**Comment by Grenadingue** [comment]
Ok, it was the exact same error on my side. Some devs didn't followed my recommandations about the `node` version (for compatibility). You need to update `node` to be `>= 6.0.0`

**Comment by vuongc** [comment]
By updating `node` to `v6.0.0` the issue got fixed
